version: '3.8'

services:
    app:
        build:
            context: ./docker/php
        container_name: lyricfa_app
        restart: unless-stopped
        working_dir: /var/www
        volumes:
            - ./:/var/www
        depends_on:
            - mysql
        networks:
            - lyricfa

    nginx:
        image: nginx:latest
        container_name: lyricfa_nginx
        restart: unless-stopped
        ports:
            - "8000:80"
        volumes:
            - ./:/var/www
            - ./docker/nginx/default.conf:/etc/nginx/conf.d/default.conf
        depends_on:
            - app
        networks:
            - lyricfa

    mysql:
        image: mysql:8
        container_name: lyricfa_mysql
        restart: unless-stopped
        environment:
            MYSQL_DATABASE: ${DB_DATABASE}
            MYSQL_ROOT_PASSWORD: ${DB_PASSWORD}
            MYSQL_USER: ${DB_USERNAME}
            MYSQL_PASSWORD: ${DB_PASSWORD}
        ports:
            - "3306:3306"
        volumes:
            - mysql_data:/var/lib/mysql
        networks:
            - lyricfa

volumes:
    mysql_data:

networks:
    lyricfa:
